Add index_notes function
pycontw/hackmd-archive-worker pull request #4
Opened 2021-12-07 02:12 UTC by Darkborderman

# What does this pull request do
Implement function to upload notes into Meilisearch.

2021-12-07 06:59 UTC, josix commented
![](https://github.trello.services/images/mini-trello-icon.png) [[infra/hackmd-worker] Setup Full-Text Search Engine for searching documents in HackMD](https://trello.com/c/3EULlA7O/11-infra-hackmd-worker-setup-full-text-search-engine-for-searching-documents-in-hackmd)

2021-12-19 12:56 UTC, Darkborderman commented on app/handler/meilisearch_handler.py
> +                })
We can add `"url": <Github archived URL>` after uploading markdowns to Github.

Currently Milisearch will only display markdown title on its frontend.

2021-12-20 17:24 UTC, josix commented on app/handler/meilisearch_handler.py
> +                })
Yeah, maybe we could put hackmd url for now until the archived version is completed.

2021-12-22 18:33 UTC, josix requested changes

2021-12-22 18:33 UTC, josix commented on app/handler/meilisearch_handler.py
> +        filepaths = glob.glob("build/*.md", recursive=True)
I guess the place for storing notes could be configurable or be a parameter.

2021-12-22 18:33 UTC, josix commented on app/handler/meilisearch_handler.py
> +                    "title": filename[:-3],
We could introduce [`pathlib`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name) to avoid using magic number like -3 in the brackets.

2021-12-26 12:21 UTC, Darkborderman commented on app/handler/meilisearch_handler.py
> +        filepaths = glob.glob("build/*.md", recursive=True)
Add `parse_path` parameter for glob path parsing.

2021-12-26 12:55 UTC, Darkborderman commented on app/handler/meilisearch_handler.py
> +                    "title": filename[:-3],
Resolved using `PosixPath.stem`

2021-12-30 01:01 UTC, merged

2021-12-30 04:01 UTC, josix commented
Thanks for merging it. I'll continue the part of deploying the search engine later.